- name: Build cEOS EVPN Asymmetric IRB Fabric (eBGP Overlay and eBGP Underlay)
  hosts: FABRIC
  tasks:
    # - name: Generate EOS configuration Snapshots
    #   tags: [snapshot]
    #   import_role:
    #     name: arista.avd.eos_snapshot

    - name: Generate AVD Structured Configurations and Fabric Documentation
      import_role:
        name: arista.avd.eos_designs

    - name: Generate Switch Intended Configurations and Documentation
      import_role:
        name: arista.avd.eos_cli_config_gen

    # - name: Deploy generated configuration to devices
    #   tags: [deploy]
    #   import_role:
    #     name: arista.avd.eos_config_deploy_eapi

    # - name: Validate states on EOS devices
    #   tags: [verify, never]
    #   import_role:
    #     name: arista.avd.eos_validate_state

- name: Server Device Config Generation
  hosts: SERVERS
  gather_facts: false
  tasks:
    - name: Building Client Device configs using jinja2
      ansible.builtin.template:
        src: templates/servers.j2
        dest: intended/structured_configs/{{ hostname }}.yml
        
    - name: Generate Switch Intended Configurations and Documentation
      import_role:
        name: arista.avd.eos_cli_config_gen

    # - name: Deploy generated configuration to devices
    #   tags: [deploy]
    #   import_role:
    #     name: arista.avd.eos_config_deploy_eapi

    # - name: Validate states on EOS devices
    #   tags: [verify, never]
    #   import_role:
    #     name: arista.avd.eos_validate_state