---
### group_vars/DC1_FABRIC.yml

# Set the Fabric Name - must match an Ansible Inventory Group
fabric_name: DC1_FABRIC

# Set Design Type to l2ls
design:
  type: l2ls

# Node Key must be l3spine to match type
l3spine:
  defaults:
    platform: cEOS-LAB
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    # Loopback is used to generate a router-id
    loopback_ipv4_pool: 1.1.1.0/24
    mlag_peer_ipv4_pool: 192.168.0.0/24
    # Needed for L3 peering across the MLAG Trunk
    mlag_peer_l3_ipv4_pool: 10.1.1.0/24
    # Used for SVI Virtual MAC address
    virtual_router_mac_address: 00:1c:73:00:dc:01
    mlag_interfaces: [Ethernet47, Ethernet48]
  node_groups:
    - group: SPINES
      nodes:
        - name: SPINE1
          id: 1
          mgmt_ip: 172.16.2.11/24
        - name: SPINE2
          id: 2
          mgmt_ip: 172.16.2.12/24

# Leaf Switches
leaf:
  defaults:
    platform: cEOS-LAB
    mlag_peer_ipv4_pool: 192.168.0.0/24
    uplink_switches: [SPINE1, SPINE2]
    uplink_interfaces: [Ethernet1, Ethernet2]
    mlag_interfaces: [Ethernet47, Ethernet48]
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384

  node_groups:
    - group: RACK1
      mlag: true
      filter:
        tags: [bluezone, greenzone]
      nodes:
        - name: LEAF1
          id: 1
          mgmt_ip: 172.16.2.101/24
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        - name: LEAF2
          id: 2
          mgmt_ip: 172.16.2.102/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
    - group: RACK2
      mlag: true
      filter:
        tags: [bluezone, orangezone]
      nodes:
        - name: LEAF3
          id: 3
          mgmt_ip: 172.16.2.103/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        - name: LEAF4
          id: 4
          mgmt_ip: 172.16.2.104/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]

#### Override for vEOS/cEOS Lab Caveats ####
p2p_uplinks_mtu: 1500

# Documentation
eos_designs_documentation:
  connected_endpoints: true
