---
# DC1_MISC.yml

type: clients

node_type_keys:
  - key: clients
    type: clients
    connected_endpoints: false
    mlag_support: false
    underlay_router: false
    uplink_type: port-channel

clients:
  node_groups:
    - group: DC1_MISC
      nodes:
        - name: HostA
          mgmt_ip: 172.16.2.241/24
          structured_config:
            ip_routing: true
            static_routes:
            - vrf: default
              destination_address_prefix: 0.0.0.0/0 
              gateway: 10.10.10.1
            ethernet_interfaces:
            - name: Ethernet1
              description: LEAF1
              type: routed
              shutdown: false
              ip_address: 10.10.10.101/24
            spanning_tree:
              mode: mstp

        - name: HostB
          mgmt_ip: 172.16.2.242/24
          structured_config:
            ip_routing: true
            static_routes:
            - vrf: default
              destination_address_prefix: 0.0.0.0/0 
              gateway: 10.20.20.1
            ethernet_interfaces:
            - name: Ethernet1
              description: LEAF2
              type: routed
              shutdown: false
              ip_address: 10.20.20.101/24
            spanning_tree:
              mode: mstp

        - name: HostC
          mgmt_ip: 172.16.2.243/24
          structured_config:
            ip_routing: true
            static_routes:
            - vrf: default
              destination_address_prefix: 0.0.0.0/0 
              gateway: 10.10.10.1
            ethernet_interfaces:
            - name: Ethernet1
              description: LEAF3
              type: routed
              shutdown: false
              ip_address: 10.10.10.102/24
            spanning_tree:
              mode: mstp

        - name: HostD
          mgmt_ip: 172.16.2.244/24
          structured_config:
            ip_routing: true
            static_routes:
            - vrf: default
              destination_address_prefix: 0.0.0.0/0 
              gateway: 10.30.30.1
            ethernet_interfaces:
            - name: Ethernet1
              description: LEAF4
              type: routed
              shutdown: false
              ip_address: 10.30.30.101/24
            spanning_tree:
              mode: mstp

        - name: FIREWALL
          mgmt_ip: 172.16.2.245/24
          structured_config:
            ip_routing: true
            port_channel_interfaces:
            - name: Port-Channel1
              description: Portchannel_Uplinks_TO_SPINE1_SPINE2
              type: switched
              shutdown: false
              mode: trunk
              vlans: 10,20,30
            ethernet_interfaces:
            - name: Ethernet1
              description: Portchannel_Uplinks_TO_SPINE1
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            - name: Ethernet2
              description: Portchannel_Uplinks_TO_SPINE2
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            vlan_interfaces:
            - name: Vlan10
              description: VLAN10_BLUE_NET
              shutdown: false 
              ip_address: 10.10.10.1/24
            - name: Vlan20
              description: VLAN20_GREEN_NET
              shutdown: false 
              ip_address: 10.20.20.1/24
            - name: Vlan30
              description: VLAN30_ORANGE_NET
              shutdown: false 
              ip_address: 10.30.30.1/24
            vlans:
            - id: 10
              name: VLAN10_BLUE_NET
            - id: 20
              name: VLAN20_GREEN_NET
            - id: 30
              name: VLAN30_ORANGE_NET