---
# SERVERS.yml

type: clients

node_type_keys:
  - key: clients
    type: clients
    connected_endpoints: false
    mlag_support: false
    underlay_router: false
    uplink_type: port-channel

clients:
  node_groups:
    - group: CPES
      nodes:
        - name: customer1_CPE1
          mgmt_ip: 172.16.2.241/24
          structured_config:
            ip_routing: true
            spanning_tree:
              mode: mstp
            ethernet_interfaces:
            - name: Ethernet1
              description: C1_L3_SERVICE
              type: routed
              shutdown: false
              ip_address: 10.0.1.3/29
              ospf_area: '0'
              ospf_network_point_to_point: false
            loopback_interfaces:
            - name: Loopback0
              description: Loopback_Customer_Testing
              shutdown: false
              ip_address: 10.10.1.1/32
              ip_address_secondaries:
                - 10.11.1.1/32
                - 10.12.1.1/32
              ospf_area: '0'
            router_ospf:
              process_ids:
              - id: 100
                passive_interface_default: true
                router_id: 172.16.2.241
                no_passive_interfaces:
                - Ethernet1
                redistribute:
                  connected: {}
                max_lsa: 12000

        - name: customer1_CPE2
          mgmt_ip: 172.16.2.242/24
          structured_config:
            ip_routing: true
            spanning_tree:
              mode: mstp
            ethernet_interfaces:
            - name: Ethernet1
              description: C1_L3_SERVICE
              type: routed
              shutdown: false
              ip_address: 10.0.1.10/30
              ospf_area: '0'
              ospf_network_point_to_point: false
            loopback_interfaces:
            - name: Loopback0
              description: Loopback_Customer_Testing
              shutdown: false
              ip_address: 10.10.2.1/32
              ip_address_secondaries:
                - 10.11.2.1/32
                - 10.12.2.1/32
              ospf_area: '0'
            router_ospf:
              process_ids:
              - id: 100
                passive_interface_default: true
                router_id: 172.16.2.242
                no_passive_interfaces:
                - Ethernet1
                redistribute:
                  connected: {}
                max_lsa: 12000


        - name: customer2_CPE1
          mgmt_ip: 172.16.2.243/24
          structured_config:
            ip_routing: true
            spanning_tree:
              mode: mstp
            ethernet_interfaces:
            - name: Ethernet1
              description: C2_L3_SERVICE
              type: routed
              shutdown: false
              ip_address: 10.1.1.3/29
            loopback_interfaces:
            - name: Loopback0
              description: Loopback_Customer_Testing
              shutdown: false
              ip_address: 10.20.1.1/32
              ip_address_secondaries:
                - 10.21.1.1/32
                - 10.22.1.1/32
            router_bgp:
              as: '65123'
              router_id: 172.16.2.243
              bgp:
                default:
                  ipv4_unicast: false
              neighbors:
              - ip_address: 10.1.1.1
                remote_as: '65001'
                description: PE1
                send_community: 'standard'
                maximum_routes: 100
              redistribute_routes:
              - source_protocol: connected
              address_family_ipv4:
                neighbors:
                - ip_address: '10.1.1.1'
                  activate: true

        - name: customer2_CPE2
          mgmt_ip: 172.16.2.244/24
          structured_config:
            ip_routing: true
            spanning_tree:
              mode: mstp
            ethernet_interfaces:
            - name: Ethernet1
              description: C2_L3_SERVICE
              type: routed
              shutdown: false
              ip_address: 10.1.1.10/30
            loopback_interfaces:
            - name: Loopback0
              description: Loopback_Customer_Testing
              shutdown: false
              ip_address: 10.20.2.1/32
              ip_address_secondaries:
                - 10.21.2.1/32
                - 10.22.2.1/32
            router_bgp:
              as: '65124'
              router_id: 172.16.2.244
              bgp:
                default:
                  ipv4_unicast: false
              neighbors:
              - ip_address: 10.1.1.9
                remote_as: '65001'
                description: PE1
                send_community: 'standard'
                maximum_routes: 100
              redistribute_routes:
              - source_protocol: connected
              address_family_ipv4:
                neighbors:
                - ip_address: '10.1.1.9'
                  activate: true

        - name: ethernet_agg
          mgmt_ip: 172.16.2.245/24
          structured_config:
            ip_routing: true
            spanning_tree:
              mode: mstp
            ethernet_interfaces:
            - name: Ethernet1
              description: customer1-CPE1
              type: switched
              shutdown: false
              mode: access
              vlans: 10
            - name: Ethernet2
              description: customer2-CPE1
              type: switched
              shutdown: false
              mode: access
              vlans: 20
            - name: Ethernet3
              description: PE1_Ethernet3
              type: switched
              shutdown: false
              mode: trunk
            - name: Ethernet4
              description: PE2_Ethernet4
              type: switched
              shutdown: false
              mode: trunk
            vlans:
            - id: 10
              name: C1_L3_SERVICE
            - id: 20
              name: C2_L3_SERVICE
