---
# DC1_CLIENTS.yml

type: clients

node_type_keys:
  - key: clients
    type: clients
    connected_endpoints: false
    mlag_support: false
    underlay_router: false
    uplink_type: port-channel

clients:
  node_groups:
    - group: DC1_PE1X_CLIENTS
      uplink_switches:
            - DC1_PE11
            - DC1_PE12
      nodes:
        - name: client1
          id: 1
          mgmt_ip: 172.16.2.241/24
          uplink_switch_interfaces:
            - Ethernet3
            - Ethernet3
          structured_config:
            static_routes:
            - vrf: default
              destination_address_prefix: 10.1.0.0/16 
              gateway: 10.1.10.1
            port_channel_interfaces:
              - name: Port-Channel1
                description: Portchannel_Uplinks_TO_DC1_PE11_DC1_PE12
                type: routed
                shutdown: false
              - name: Port-Channel1.110
                description: Portchannel_Uplinks_TO_DC1_PE11_DC1_PE12 - dot1q VLAN 110
                type: l3dot1q
                shutdown: false
                encapsulation_dot1q_vlan: 110
                ip_address: 10.1.10.101/24
            ethernet_interfaces:
            - name: Ethernet1
              description: Portchannel_Uplinks_TO_DC1_PE11
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: 'on'
            - name: Ethernet2
              description: Portchannel_Uplinks_TO_DC1_PE12
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: 'on'

        - name: client2
          id: 2
          mgmt_ip: 172.16.2.242/24
          uplink_switch_interfaces:
            - Ethernet4
            - Ethernet4
          structured_config:
            static_routes:
            - vrf: default
              destination_address_prefix: 10.1.0.0/16 
              gateway: 10.1.11.1

            port_channel_interfaces:
            - name: Port-Channel1
              description: Portchannel_Uplinks_TO_DC1_PE11_DC1_PE12
              type: routed
              shutdown: false
            - name: Port-Channel1.111
              description: Portchannel_Uplinks_TO_DC1_PE11_DC1_PE12 - dot1q VLAN 111
              type: l3dot1q
              shutdown: false
              encapsulation_dot1q_vlan: 111
              ip_address: 10.1.11.102/24

            ethernet_interfaces:
            - name: Ethernet1
              description: Portchannel_Uplinks_TO_DC1_PE11
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: 'on'
            - name: Ethernet2
              description: Portchannel_Uplinks_TO_DC1_PE12
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: 'on'

    - group: DC1_PE2X_CLIENTS
      uplink_switches:
            - DC1_PE21
            - DC1_PE22
      nodes:
        - name: client3
          id: 3
          mgmt_ip: 172.16.2.243/24
          uplink_switch_interfaces:
            - Ethernet3
            - Ethernet3
          structured_config:
            static_routes:
            - vrf: default
              destination_address_prefix: 10.1.0.0/16 
              gateway: 10.1.12.1

            port_channel_interfaces:
            - name: Port-Channel1
              description: Portchannel_Uplinks_TO_DC1_PE21_DC1_PE22
              type: routed
              shutdown: false
            - name: Port-Channel1.112
              description: Portchannel_Uplinks_TO_DC1_PE21_DC1_PE22 - dot1q VLAN 112
              type: l3dot1q
              shutdown: false
              encapsulation_dot1q_vlan: 112
              ip_address: 10.1.12.103/24

            ethernet_interfaces:
            - name: Ethernet1
              description: Portchannel_Uplinks_TO_DC1_PE21
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: 'on'
            - name: Ethernet2
              description: Portchannel_Uplinks_TO_DC1_PE22
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: 'on'

        - name: client4
          id: 4
          mgmt_ip: 172.16.2.244/24
          uplink_switch_interfaces:
            - Ethernet4
            - Ethernet4
          structured_config:
            static_routes:
            - vrf: default
              destination_address_prefix: 10.1.0.0/16 
              gateway: 10.1.13.1

            port_channel_interfaces:
            - name: Port-Channel1
              description: Portchannel_Uplinks_TO_DC1_PE21_DC1_PE22
              type: routed
              shutdown: false
            - name: Port-Channel1.113
              description: Portchannel_Uplinks_TO_DC1_PE21_DC1_PE22 - dot1q VLAN 113
              type: l3dot1q
              shutdown: false
              encapsulation_dot1q_vlan: 113
              ip_address: 10.1.13.104/24

            ethernet_interfaces:
            - name: Ethernet1
              description: Portchannel_Uplinks_TO_DC1_PE21
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: 'on'
            - name: Ethernet2
              description: Portchannel_Uplinks_TO_DC1_PE22
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: 'on'