---
# Please note, comments below are intended for site documentation only
- name: Device Config Generation
  hosts: DC1_CORE
  gather_facts: false
  tasks:
    - name: Building Core Device configs using jinja2
      ansible.builtin.template:
        src: "../templates/core.j2"
        dest: "intended/structured_configs/{{ hostname }}.yml"

- name: Client Devices Config Generation
  hosts: DC1_CLIENTS
  gather_facts: false
  tasks:
    - name: Building Client Device configs using jinja2
      ansible.builtin.template:
        src: "../templates/client_devices.j2"
        dest: "intended/structured_configs/{{ hostname }}.yml"

- name: PE Devices Config Generation
  hosts: DC1_PES
  gather_facts: false
  tasks:
    - name: Building PE Device configs using jinja2
      ansible.builtin.template:
        src: "../templates/PE_devices.j2"
        dest: "intended/structured_configs/{{ hostname }}.yml"

- name: Run AVD
  hosts: DC1_FABRIC
  gather_facts: false
  tasks:
    - name: Generate Device Configurations and Documentation 
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen

    - name: Deploy Configurations to Devices
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_eapi
