---
- name: Cleanup Old Configuration and Device Documentation
  hosts: DC1_FABRIC
  tasks:
    - name: Remove Old Switch Configuration
      file:
        path: intended/configs/{{ inventory_hostname }}.cfg
        state: absent
    - name: Remove Old Switch Documentation
      file:
        path: documentation/devices/{{ inventory_hostname }}.md
        state: absent

- name: Device Config Generation
  hosts: DC1_CORE
  gather_facts: false
  tasks:
    - name: Building Core Device configs using jinja2
      ansible.builtin.template:
        src: "../templates/core.j2"
        dest: "intended/structured_configs/{{ hostname }}.yml"

- name: Client Devices Config Generation
  hosts: DC1_CLIENTS
  gather_facts: false
  tasks:
    - name: Building Client Device configs using jinja2
      ansible.builtin.template:
        src: "../templates/client_devices.j2"
        dest: "intended/structured_configs/{{ hostname }}.yml"

- name: PE Devices Config Generation
  hosts: DC1_PES
  gather_facts: false
  tasks:
    - name: Building PE Device configs using jinja2
      ansible.builtin.template:
        src: "../templates/PE_devices.j2"
        dest: "intended/structured_configs/{{ hostname }}.yml"

- name: Deploy Configs to Devices
  hosts: DC1_FABRIC
  gather_facts: false
  tasks:

    # - name: Generate EOS configuration Snapshots
    #   tags: [snapshot]
    #   import_role:
    #     name: arista.avd.eos_snapshot

    - name: Generate Device Configurations and Documentation 
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen

    - name: Deploy Configurations to Devices
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_eapi

    # - name: Validate states on EOS devices
    #   tags: [verify, never]
    #   import_role:
    #     name: arista.avd.eos_validate_state