---
# DC1_MISC.yml

type: clients

node_type_keys:
  - key: clients
    type: clients
    connected_endpoints: false
    mlag_support: false
    underlay_router: false
    uplink_type: port-channel

clients:
  node_groups:
    - group: DC1_MISC
      nodes:
        - name: WAN_CORE
          mgmt_ip: 172.16.2.245/24
          structured_config:
            ip_routing: true
            # static_routes:
            # - vrf: default
            #   destination_address_prefix: 0.0.0.0/0 
            #   gateway: 10.10.10.1
            spanning_tree:
              mode: mstp
            ethernet_interfaces:
            - name: Ethernet1/1
              description: P2P_LINK_TO_SPINE1_Ethernet52_1
              type: routed
              shutdown: false
              ip_address: 10.0.0.2/31
              ospf_area: '0'
              ospf_network_point_to_point: true
            - name: Ethernet1/2
              description: P2P_LINK_TO_SPINE2_Ethernet52_1
              type: routed
              shutdown: false
              ip_address: 10.0.0.4/31
              ospf_area: '0'
              ospf_network_point_to_point: true
            loopback_interfaces:
            - name: Loopback0
              description: Loopback_Customer_Testing
              shutdown: false
              ip_address: 10.101.1.1/32
              ip_address_secondaries:
                - 10.102.1.1/32
                - 10.103.1.1/32
              ospf_area: '0'
            router_ospf:
              process_ids:
              - id: 100
                passive_interface_default: true
                router_id: 172.16.2.245
                no_passive_interfaces:
                - Ethernet1/1
                - Ethernet1/2
                redistribute:
                  connected: {}
                max_lsa: 12000