---
# Ansible connectivity definitions
# eAPI connectivity via HTTPS is specified (as opposed to CLI via SSH)
ansible_connection: ansible.netcommon.httpapi
# Specifies that we are indeed using Arista EOS
ansible_network_os: arista.eos.eos
# This user/password must exist on the switches to enable Ansible access
ansible_user: ansible
ansible_password: ansible
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
# Use SSL (HTTPS)
ansible_httpapi_use_ssl: true
# Do not try to validate certs
ansible_httpapi_validate_certs: false

# SWA notes - add ciphers to communicate over httpapi towards the EOS device. 
ansible_httpapi_ciphers: AES256-SHA:DHE-RSA-AES256-SHA:AES128-SHA:DHE-RSA-AES128-SHA

# AAA Authorization
aaa_authorization:
  exec:
    default: local

# Local users
local_users:
  # Define a new user, which is called "ansible"
  - name: ansible
    privilege: 15
    role: network-admin
    # Password set to "ansible". Same string as the device generates when configuring a username.
    sha512_password: $6$7u4j1rkb3VELgcZE$EJt2Qff8kd/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920
  - name: admin
    privilege: 15
    role: network-admin
    no_password: true
  - name: admin2
    privilege: 15
    role: network-admin
    no_password: true

# OOB Management network default gateway.
mgmt_gateway: 172.16.2.1
mgmt_interface: Management0
mgmt_interface_vrf: MGMT
vrfs:
  - name: MGMT
    ip_routing: false

ip_name_servers:
  - ip_address: 1.1.1.1
    vrf: MGMT
  - ip_address: 8.8.8.8
    vrf: MGMT

ntp:
  servers:
  - name: time.google.com
    preferred: true
    vrf: MGMT
    iburst: true
static_routes:
  - vrf: MGMT
    destination_address_prefix: 0.0.0.0/0
    gateway: 172.16.2.1
ip_routing: true
service_routing_protocols_model: multi-agent
management_api_http:
  enable_https: true
  enable_vrfs:
    - name: MGMT
# spanning_tree:
#   mode: mstp


# # Multi-line string with one or more alias commands.
# aliases: |
#   alias siib show ip interface brief
#   alias cc clear counters
#   alias cp clear platform trident counters 
#   alias senz show interface counter error | nz 
#   alias snz show interface counter | nz 
#   alias sqnz show interface counter queue | nz 
#   alias srnz show interface counter rate | nz
#   alias shrte show ip route
#   alias showcon show interfaces status | grep connected    
#   alias sa show active 
#   alias clrcounters clear counters
#   alias wrtme write mem
#   alias spc show port-channel %1 detail all   
#   alias ports show int sta | grep "connected\| disabled" 
#   alias shmc show int | awk '/^[A-Z]/ { intf = $1 } /, address is/ { print intf, $6 }'
#   alias term_logs sh agent TerminAttr logs | tail
