hostname: DC1_PE11
mgmt_ip_address: 172.16.2.101/24
tenant_name: Tenant_A
eth1_description: P2P_LINK_TO_DC1_P1_Ethernet1
eth1_ip_address: 172.31.255.1/31
eth2_description: P2P_LINK_TO_DC1_P2_Ethernet1
eth2_ip_address: 172.31.255.3/31
eth3_description: P2P_LINK_TO_CORE_Ethernet1
eth3_ip_address: 10.2.0.0/31
eth5_description: client1_Ethernet1
lo0_ip_address: 192.168.255.3
vlan111_ip_address: 10.1.11.1/24
vlan111_shutdown: false
virtual_mac: 00:00:00:00:00:01
evpn_soo: 192.168.254.3:1
isis_net_id: 49.0001.0001.0001.0001.00
core_bgp_ip: 10.2.0.1
core_bgp_desc: CORE_Ethernet1
bgp_asn: 65001
overlay_peer_asn: 65001
rt_mac_vrf: "10011:10011"
rd_mac_vrf: 10011
rd_l3vrf: 10
rt_l3vrf: "10:10"