---
# Please note, comments below are intended for site documentation only
- name: Spine Config Generation
  hosts: SPINES
  gather_facts: false
  tasks:
    - name: Building Spine configs using jinja2
      ansible.builtin.template:
        src: templates/spines.j2
        dest: intended/structured_configs/{{ hostname }}.yml

- name: Run AVD # (1)!
  hosts: SPINES
  gather_facts: false
  tasks:
    - name: Generate Device Configurations and Documentation # (3)!
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen

    # - name: Deploy Configurations to Devices # (4)!
    #   ansible.builtin.import_role:
    #     name: arista.avd.eos_config_deploy_eapi
