hostname: DC1_PE11
mgmt_ip_address: 172.16.2.103/24
tenant_name: Tenant_A
eth1_description: P2P_LINK_TO_DC1_PE12_Ethernet1
eth1_ip_address: 10.1.0.0/31
eth2_description: P2P_LINK_TO_CORE_Ethernet1
eth2_ip_address: 10.2.0.0/31
eth5_description: client1_Ethernet1
eth6_description: P2P_LINK_TO_DC2_PE21_Ethernet6
eth6_ip_address: 172.100.100.0/31
lo0_ip_address: 10.255.0.5
lo10_ip_address: 10.255.10.5
vlan111_ip_address: 10.1.11.1/24
virtual_mac: 00:00:00:00:00:01
overlay_peer: DC1_PE12
overlay_peer_ip: 10.255.0.6
overlay_peer_desc: DC1_PE12
overlay_core: DC2_PE21
overlay_core_ip: 10.255.128.15
overlay_core_desc: DC2_PE21
isis_net_id: 49.0001.0001.0001.0005.00
core_bgp_ip: 10.2.0.1
core_bgp_desc: CORE_Ethernet1
bgp_asn: 65102
overlay_peer_asn: 65102
overlay_core_asn: 65202
rt_mac_vrf: "10011:10011"
rt_mac_vrf_domain: "10011:10011"
rd_mac_vrf: 10011
rd_mac_vrf_domain: 10011
rd_l3vrf: 10
rt_l3vrf: "10:10"