---

type: clients

node_type_keys:
  - key: clients
    type: clients
    connected_endpoints: false
    mlag_support: false
    underlay_router: false
    uplink_type: port-channel

clients:
  node_groups:
    - group: DC2_LEAF1_CLIENTS
      uplink_switches:
            - dc2-leaf1a
            - dc2-leaf1b
      uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
      nodes:
        - name: dc2-client1
          id: 11
          mgmt_ip: 172.16.2.241/24
          structured_config:
            ip_routing: true
            port_channel_interfaces:
            - name: Port-Channel1
              description: Portchannel_Uplinks_TO_dc2-leaf1a_dc2-leaf1b
              type: switched
              shutdown: false
              mode: trunk
              vlans: 120
            ethernet_interfaces:
            - name: Ethernet1
              description: Portchannel_Uplinks_TO_dc2-leaf1a
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            - name: Ethernet2
              description: Portchannel_Uplinks_TO_dc2-leaf1b
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            vlan_interfaces:
            - name: Vlan120
              description: VRF_RED_VLAN_120
              shutdown: false 
              ip_address: 10.1.20.101/24
            vlans:
            - id: 120
              name: VRF_RED_VLAN_120
            spanning_tree:
              mode: mstp

        - name: dc2-client2
          id: 12
          mgmt_ip: 172.16.2.242/24
          structured_config:
            ip_routing: true
            port_channel_interfaces:
            - name: Port-Channel1
              description: Portchannel_Uplinks_TO_dc2-leaf1a_dc2-leaf1b
              type: switched
              shutdown: false
              mode: trunk
              vlans: 121
            ethernet_interfaces:
            - name: Ethernet1
              description: Portchannel_Uplinks_TO_dc2-leaf1a
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            - name: Ethernet2
              description: Portchannel_Uplinks_TO_dc2-leaf1b
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            vlan_interfaces:
            - name: Vlan121
              description: VRF_BLUE_VLAN_121
              shutdown: false 
              ip_address: 10.1.21.101/24
            vlans:
            - id: 121
              name: VRF_BLUE_VLAN_121
            spanning_tree:
              mode: mstp


    - group: DC2_LEAF2_CLIENTS
      uplink_switches:
            - dc2-leaf2a
            - dc2-leaf2b
      uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
      nodes:
        - name: dc2-client3
          id: 13
          mgmt_ip: 172.16.2.243/24
          structured_config:
            ip_routing: true
            port_channel_interfaces:
            - name: Port-Channel1
              description: Portchannel_Uplinks_TO_dc2-leaf2a_dc2-leaf2b
              type: switched
              shutdown: false
              mode: trunk
              vlans: 122
            ethernet_interfaces:
            - name: Ethernet1
              description: Portchannel_Uplinks_TO_dc2-leaf2a
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            - name: Ethernet2
              description: Portchannel_Uplinks_TO_dc2-leaf2b
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            vlan_interfaces:
            - name: Vlan122
              description: VRF_RED_VLAN_122
              shutdown: false 
              ip_address: 10.1.22.101/24
            vlans:
            - id: 122
              name: VRF_RED_VLAN_122
            spanning_tree:
              mode: mstp

        - name: dc2-client4
          id: 14
          mgmt_ip: 172.16.2.244/24
          structured_config:
            ip_routing: true
            port_channel_interfaces:
            - name: Port-Channel1
              description: Portchannel_Uplinks_TO_dc2-leaf2a_dc2-leaf2b
              type: switched
              shutdown: false
              mode: trunk
              vlans: 123
            ethernet_interfaces:
            - name: Ethernet1
              description: Portchannel_Uplinks_TO_dc2-leaf2a
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            - name: Ethernet2
              description: Portchannel_Uplinks_TO_dc2-leaf2b
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            vlan_interfaces:
            - name: Vlan123
              description: VRF_BLUE_VLAN_123
              shutdown: false 
              ip_address: 10.1.23.101/24
            vlans:
            - id: 123              
              name: VRF_BLUE_VLAN_123
            spanning_tree:
              mode: mstp