---
# SERVERS.yml

type: clients

node_type_keys:
  - key: clients
    type: clients
    connected_endpoints: false
    mlag_support: false
    underlay_router: false
    uplink_type: port-channel

clients:
  node_groups:
    - group: DC1_LEAF1_SERVERS
      uplink_switches:
            - dc1-leaf1a
            - dc1-leaf1b
            - dc1-leaf1c
      uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
            - Ethernet5
      nodes:
        - name: dc1-leaf1-server1
          id: 1
          mgmt_ip: 172.16.2.241/24
          structured_config:
            ip_routing: true
            port_channel_interfaces:
            - name: Port-Channel1
              description: Portchannel_Uplinks_TO_dc1-leaf1a_dc1-leaf1b
              type: switched
              shutdown: false
              mode: trunk
              vlans: 11-12,21-22
              native_vlan: 4092
            ethernet_interfaces:
            - name: Ethernet1
              description: Portchannel_Uplinks_TO_dc1-leaf1a
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            - name: Ethernet2
              description: Portchannel_Uplinks_TO_dc1-leaf1b
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            - name: Ethernet3
              description: dc1-leaf1-server1_iLO
              type: routed
              shutdown: false
              vrf: ILO
              ip_address: 10.10.11.105/24
            vlan_interfaces:
            - name: Vlan11
              description: VRF10_VLAN11
              shutdown: false 
              ip_address: 10.10.11.101/24
            - name: Vlan12
              description: VRF10_VLAN12
              shutdown: false 
              ip_address: 10.10.12.101/24
            - name: Vlan21
              description: VRF11_VLAN21
              shutdown: false 
              ip_address: 10.10.21.101/24
            - name: Vlan22
              description: VRF11_VLAN22
              shutdown: false 
              ip_address: 10.10.22.101/24
            vlans:
            - id: 11
              name: VRF10_VLAN11
            - id: 12
              name: VRF10_VLAN12
            - id: 21
              name: VRF11_VLAN21
            - id: 22
              name: VRF11_VLAN22
            - id: 4092
              name: NATIVE_VLAN
            vrfs:
            - name: ILO
              ip_routing: true
            spanning_tree:
              mode: mstp

    - group: DC1_LEAF2_SERVERS
      uplink_switches:
            - dc1-leaf2a
            - dc1-leaf2b
            - dc1-leaf2c
      uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
            - Ethernet5
      nodes:
        - name: dc1-leaf2-server1
          id: 2
          mgmt_ip: 172.16.2.242/24
          structured_config:
            ip_routing: true
            port_channel_interfaces:
            - name: Port-Channel1
              description: Portchannel_Uplinks_TO_dc1-leaf2a_dc1-leaf2b
              type: switched
              shutdown: false
              mode: trunk
              vlans: 11-12,21-22
              native_vlan: 4092
            ethernet_interfaces:
            - name: Ethernet1
              description: Portchannel_Uplinks_TO_dc1-leaf2a
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            - name: Ethernet2
              description: Portchannel_Uplinks_TO_dc1-leaf2b
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            - name: Ethernet3
              description: dc1-leaf2-server1_iLO
              type: routed
              shutdown: false
              vrf: ILO
              ip_address: 10.10.11.106/24
            vlan_interfaces:
            - name: Vlan11
              description: VRF10_VLAN11
              shutdown: false 
              ip_address: 10.10.11.102/24
            - name: Vlan12
              description: VRF10_VLAN12
              shutdown: false 
              ip_address: 10.10.12.102/24
            - name: Vlan21
              description: VRF11_VLAN21
              shutdown: false 
              ip_address: 10.10.21.102/24
            - name: Vlan22
              description: VRF11_VLAN22
              shutdown: false 
              ip_address: 10.10.22.102/24
            vlans:
            - id: 11
              name: VRF10_VLAN11
            - id: 12
              name: VRF10_VLAN12
            - id: 21
              name: VRF11_VLAN21
            - id: 22
              name: VRF11_VLAN22
            - id: 4092
              name: NATIVE_VLAN
            vrfs:
            - name: ILO
              ip_routing: true
            spanning_tree:
              mode: mstp

    - group: DC2_LEAF1_SERVERS
      uplink_switches:
            - dc2-leaf1a
            - dc2-leaf1b
            - dc2-leaf1c
      uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
            - Ethernet5
      nodes:
        - name: dc2-leaf1-server1
          id: 1
          mgmt_ip: 172.16.2.243/24
          structured_config:
            ip_routing: true
            port_channel_interfaces:
            - name: Port-Channel1
              description: Portchannel_Uplinks_TO_dc2-leaf1a_dc2-leaf1b
              type: switched
              shutdown: false
              mode: trunk
              vlans: 11-12,21-22
              native_vlan: 4092
            ethernet_interfaces:
            - name: Ethernet1
              description: Portchannel_Uplinks_TO_dc2-leaf1a
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            - name: Ethernet2
              description: Portchannel_Uplinks_TO_dc2-leaf1b
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            - name: Ethernet3
              description: dc2-leaf1-server1_iLO
              type: routed
              shutdown: false
              vrf: ILO
              ip_address: 10.10.11.115/24
            vlan_interfaces:
            - name: Vlan11
              description: VRF10_VLAN11
              shutdown: false 
              ip_address: 10.10.11.111/24
            - name: Vlan12
              description: VRF10_VLAN12
              shutdown: false 
              ip_address: 10.10.12.111/24
            - name: Vlan21
              description: VRF11_VLAN21
              shutdown: false 
              ip_address: 10.10.21.111/24
            - name: Vlan22
              description: VRF11_VLAN22
              shutdown: false 
              ip_address: 10.10.22.111/24
            vlans:
            - id: 11
              name: VRF10_VLAN11
            - id: 12
              name: VRF10_VLAN12
            - id: 21
              name: VRF11_VLAN21
            - id: 22
              name: VRF11_VLAN22
            - id: 4092
              name: NATIVE_VLAN
            vrfs:
            - name: ILO
              ip_routing: true
            spanning_tree:
              mode: mstp

    - group: DC2_LEAF2_SERVERS
      uplink_switches:
            - dc2-leaf2a
            - dc2-leaf2b
            - dc2-leaf2c
      uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
            - Ethernet5
      nodes:
        - name: dc2-leaf2-server1
          id: 2
          mgmt_ip: 172.16.2.244/24
          structured_config:
            ip_routing: true
            port_channel_interfaces:
            - name: Port-Channel1
              description: Portchannel_Uplinks_TO_dc2-leaf2a_dc2-leaf2b
              type: switched
              shutdown: false
              mode: trunk
              vlans: 11-12,21-22
              native_vlan: 4092
            ethernet_interfaces:
            - name: Ethernet1
              description: Portchannel_Uplinks_TO_dc2-leaf2a
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            - name: Ethernet2
              description: Portchannel_Uplinks_TO_dc2-leaf2b
              type: port-channel-member
              shutdown: false
              channel_group:
                id: 1
                mode: active
            - name: Ethernet3
              description: dc2-leaf2-server1_iLO
              type: routed
              shutdown: false
              vrf: ILO
              ip_address: 10.10.11.116/24
            vlan_interfaces:
            - name: Vlan11
              description: VRF10_VLAN11
              shutdown: false 
              ip_address: 10.10.11.112/24
            - name: Vlan12
              description: VRF10_VLAN12
              shutdown: false 
              ip_address: 10.10.12.112/24
            - name: Vlan21
              description: VRF11_VLAN21
              shutdown: false 
              ip_address: 10.10.21.112/24
            - name: Vlan22
              description: VRF11_VLAN22
              shutdown: false 
              ip_address: 10.10.22.112/24
            vlans:
            - id: 11
              name: VRF10_VLAN11
            - id: 12
              name: VRF10_VLAN12
            - id: 21
              name: VRF11_VLAN21
            - id: 22
              name: VRF11_VLAN22
            - id: 4092
              name: NATIVE_VLAN
            vrfs:
            - name: ILO
              ip_routing: true
            spanning_tree:
              mode: mstp
